"""
Pydantic models for Lead Autopilot.

Defines data schemas for lead submission, enriched company data,
pipeline status tracking, and API responses.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, EmailStr, Field, HttpUrl


# ── Lead Submission (Form Input) ─────────────────────────────────────────────

class LeadSubmission(BaseModel):
    """Schema for the lead intake form submission."""

    name: str = Field(..., min_length=2, max_length=100, description="Full name of the prospect")
    email: EmailStr = Field(..., description="Prospect's email address")
    company: str = Field(..., min_length=1, max_length=200, description="Company name")
    website: HttpUrl = Field(..., description="Company website URL")
    industry: str = Field(default="General", max_length=100, description="Industry/sector")
    company_size: str = Field(default="Unknown", max_length=50, description="Approximate company size")
    message: str = Field(default="", max_length=2000, description="Optional message or pain points")


# ── Enriched Company Data ────────────────────────────────────────────────────

class ScrapedData(BaseModel):
    """Data extracted from the company's website."""

    title: str = ""
    meta_description: str = ""
    hero_text: str = ""
    about_text: str = ""
    services: list[str] = Field(default_factory=list)
    tech_stack: list[str] = Field(default_factory=list)
    social_links: dict[str, str] = Field(default_factory=dict)
    contact_info: dict[str, str] = Field(default_factory=dict)
    key_pages: list[str] = Field(default_factory=list)
    raw_text_snippet: str = ""


class SWOTAnalysis(BaseModel):
    """SWOT analysis generated by AI."""

    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    opportunities: list[str] = Field(default_factory=list)
    threats: list[str] = Field(default_factory=list)


class Scorecard(BaseModel):
    digital_maturity: int = Field(default=5, ge=1, le=10)
    ai_readiness: int = Field(default=5, ge=1, le=10)
    seo_foundation: int = Field(default=5, ge=1, le=10)

class ActionItem(BaseModel):
    timeline: str = ""
    recommendation: str = ""
    impact: str = "Medium"
    effort: str = "Medium"

class AIAnalysis(BaseModel):
    """AI-generated analysis and insights."""

    executive_summary: str = ""
    current_state_assessment: str = ""
    swot: SWOTAnalysis = Field(default_factory=SWOTAnalysis)
    key_findings: list[dict] = Field(default_factory=list) # e.g. [{"category": "SEO", "observation": "..."}]
    risk_areas: list[str] = Field(default_factory=list)
    strategic_opportunities: list[str] = Field(default_factory=list)
    scorecard: Scorecard = Field(default_factory=Scorecard)
    action_roadmap: list[ActionItem] = Field(default_factory=list)


class EnrichedCompanyData(BaseModel):
    """Combined scraped + AI-analyzed data for a company."""

    lead: LeadSubmission
    scraped: ScrapedData = Field(default_factory=ScrapedData)
    analysis: AIAnalysis = Field(default_factory=AIAnalysis)
    enriched_at: datetime = Field(default_factory=datetime.utcnow)
    data_quality_score: float = Field(default=0.0, ge=0.0, le=1.0, description="0.0-1.0 quality rating")
    confidence_level: str = Field(default="Low")
    confidence_reason: str = Field(default="Limited data available.")


# ── Pipeline Status ──────────────────────────────────────────────────────────

class PipelineStep(str, Enum):
    """Individual steps in the processing pipeline."""

    SUBMITTED = "submitted"
    VALIDATING = "validating"
    ENRICHING = "enriching"
    GENERATING_PDF = "generating_pdf"
    SENDING_EMAIL = "sending_email"
    LOGGING = "logging"
    COMPLETE = "complete"
    ERROR = "error"


class LeadStatus(BaseModel):
    """Tracks the current processing status of a lead."""

    lead_id: str
    current_step: PipelineStep = PipelineStep.SUBMITTED
    steps_completed: list[PipelineStep] = Field(default_factory=list)
    error_message: Optional[str] = None
    pdf_path: Optional[str] = None
    email_sent: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    quality_score: dict = Field(default_factory=dict)
    confidence_level: Optional[str] = None
    confidence_reason: Optional[str] = None
    pipeline_step_statuses: dict = Field(default_factory=dict)
    errors: list = Field(default_factory=list)
    warnings: list = Field(default_factory=list)
    is_retry: bool = False
    original_lead_id: Optional[str] = None


# ── API Responses ────────────────────────────────────────────────────────────

class LeadSubmitResponse(BaseModel):
    """Response after successfully submitting a lead."""

    lead_id: str
    message: str = "Lead submitted successfully. Processing has begun."
    status: PipelineStep = PipelineStep.SUBMITTED


class StatusResponse(BaseModel):
    """Response for status polling endpoint."""

    lead_id: str
    current_step: PipelineStep
    steps_completed: list[PipelineStep]
    error_message: Optional[str] = None
    is_complete: bool = False
